#undef MEMMAP_VENDOR_ID
#define MEMMAP_VENDOR_ID        (30u)

# undef MEMMAP_AR_RELEASE_MAJOR_VERSION
# undef MEMMAP_AR_RELEASE_MINOR_VERSION
# undef MEMMAP_AR_RELEASE_REVISION_VERSION

# define MEMMAP_AR_RELEASE_MAJOR_VERSION       (4u)
# define MEMMAP_AR_RELEASE_MINOR_VERSION       (0u)
# define MEMMAP_AR_RELEASE_REVISION_VERSION    (3u)

# undef MEM_AR_RELEASE_MAJOR_VERSION
# undef MEM_AR_RELEASE_MINOR_VERSION
# undef MEM_AR_RELEASE_PATCH_VERSION

# define MEM_AR_RELEASE_MAJOR_VERSION          MEMMAP_AR_RELEASE_MAJOR_VERSION
# define MEM_AR_RELEASE_MINOR_VERSION          MEMMAP_AR_RELEASE_MINOR_VERSION
# define MEM_AR_RELEASE_PATCH_VERSION          MEMMAP_AR_RELEASE_REVISION_VERSION

# undef MEMMAP_SW_MAJOR_VERSION
# undef MEMMAP_SW_MINOR_VERSION
# undef MEMMAP_SW_PATCH_VERSION

# define MEMMAP_SW_MAJOR_VERSION     (1u)
# define MEMMAP_SW_MINOR_VERSION     (11u)
# define MEMMAP_SW_PATCH_VERSION     (0u)

# undef MEM_SW_MAJOR_VERSION
# undef MEM_SW_MINOR_VERSION
# undef MEM_SW_PATCH_VERSION

# define MEM_SW_MAJOR_VERSION        MEMMAP_SW_MAJOR_VERSION
# define MEM_SW_MINOR_VERSION        MEMMAP_SW_MINOR_VERSION
# define MEM_SW_PATCH_VERSION        MEMMAP_SW_PATCH_VERSION

#define MEMMAP_ERROR

#ifdef _CDD_START_SEC_CODE
# undef _CDD_START_SEC_CODE
# define START_SEC_CODE
#endif
#ifdef _CDD_STOP_SEC_CODE
# undef _CDD_STOP_SEC_CODE
# define STOP_SEC_CODE
#endif

#ifdef FEE_30_SMALLSECTOR_START_SEC_CODE
    #undef FEE_30_SMALLSECTOR_START_SEC_CODE
    #define START_SEC_CODE
#endif
#ifdef FEE_30_SMALLSECTOR_STOP_SEC_CODE
    #undef FEE_30_SMALLSECTOR_STOP_SEC_CODE
    #define STOP_SEC_CODE
#endif

#ifdef FEE_30_SMALLSECTOR_START_SEC_CONST_8BIT
    #undef FEE_30_SMALLSECTOR_START_SEC_CONST_8BIT
    #define START_SEC_CONST_8BIT
#endif
#ifdef FEE_30_SMALLSECTOR_STOP_SEC_CONST_8BIT
    #undef FEE_30_SMALLSECTOR_STOP_SEC_CONST_8BIT
    #define STOP_SEC_CONST
#endif

#ifdef FEE_30_SMALLSECTOR_START_SEC_CONST_16BIT
    #undef FEE_30_SMALLSECTOR_START_SEC_CONST_16BIT
    #define START_SEC_CONST_16BIT
#endif
#ifdef FEE_30_SMALLSECTOR_STOP_SEC_CONST_16BIT
    #undef FEE_30_SMALLSECTOR_STOP_SEC_CONST_16BIT
    #define STOP_SEC_CONST
#endif

#ifdef FEE_30_SMALLSECTOR_START_SEC_CONST_32BIT
    #undef FEE_30_SMALLSECTOR_START_SEC_CONST_32BIT
    #define START_SEC_CONST_32BIT
#endif
#ifdef FEE_30_SMALLSECTOR_STOP_SEC_CONST_32BIT
    #undef FEE_30_SMALLSECTOR_STOP_SEC_CONST_32BIT
    #define STOP_SEC_CONST
#endif

#ifdef FEE_30_SMALLSECTOR_START_SEC_CONST_UNSPECIFIED
    #undef FEE_30_SMALLSECTOR_START_SEC_CONST_UNSPECIFIED
    #define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef FEE_30_SMALLSECTOR_STOP_SEC_CONST_UNSPECIFIED
    #undef FEE_30_SMALLSECTOR_STOP_SEC_CONST_UNSPECIFIED
    #define STOP_SEC_CONST
#endif

#ifdef FEE_30_SMALLSECTOR_START_SEC_VAR_NOINIT_UNSPECIFIED
    #undef FEE_30_SMALLSECTOR_START_SEC_VAR_NOINIT_UNSPECIFIED
    #define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef FEE_30_SMALLSECTOR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
    #undef FEE_30_SMALLSECTOR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#ifdef FEE_30_SMALLSECTOR_START_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef FEE_30_SMALLSECTOR_START_SEC_VAR_FAST_INIT_UNSPECIFIED
    #define START_SEC_VAR_FAST_INIT_UNSPECIFIED
#endif
#ifdef FEE_30_SMALLSECTOR_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef FEE_30_SMALLSECTOR_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#ifdef MEMIF_START_SEC_CONST_8BIT
    #undef MEMIF_START_SEC_CONST_8BIT
    #define START_SEC_CONST_8BIT
#endif

#ifdef MEMIF_STOP_SEC_CONST_8BIT
    #undef MEMIF_STOP_SEC_CONST_8BIT
    #define STOP_SEC_CONST
#endif

#ifdef MEMIF_START_SEC_CONST_32BIT
    #undef MEMIF_START_SEC_CONST_32BIT
    #define START_SEC_CONST_32BIT
#endif

#ifdef MEMIF_STOP_SEC_CONST_32BIT
    #undef MEMIF_STOP_SEC_CONST_32BIT
    #define STOP_SEC_CONST
#endif

#ifdef MEMIF_START_SEC_CODE
    #undef MEMIF_START_SEC_CODE
    #define START_SEC_CODE
#endif

#ifdef MEMIF_STOP_SEC_CODE
    #undef MEMIF_STOP_SEC_CODE
    #define STOP_SEC_CODE
#endif

#ifdef NVM_START_SEC_CODE
    #undef NVM_START_SEC_CODE
    #define START_SEC_CODE
#endif
#ifdef NVM_STOP_SEC_CODE
    #undef NVM_STOP_SEC_CODE
    #define STOP_SEC_CODE
#endif

#ifdef NVM_START_SEC_CONST_8
    #undef NVM_START_SEC_CONST_8
    #define START_SEC_CONST_8BIT
#endif
#ifdef NVM_STOP_SEC_CONST_8
    #undef NVM_STOP_SEC_CONST_8
    #define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_CONST_16
    #undef NVM_START_SEC_CONST_16
    #define START_SEC_CONST_16BIT
#endif
#ifdef NVM_STOP_SEC_CONST_16
    #undef NVM_STOP_SEC_CONST_16
    #define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_CONST_UNSPECIFIED
    #undef NVM_START_SEC_CONST_UNSPECIFIED
    #define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_CONST_UNSPECIFIED
    #undef NVM_STOP_SEC_CONST_UNSPECIFIED
    #define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_CONST_DESCRIPTOR_TABLE
    #undef NVM_START_SEC_CONST_DESCRIPTOR_TABLE
    #define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_CONST_DESCRIPTOR_TABLE
    #undef NVM_STOP_SEC_CONST_DESCRIPTOR_TABLE
    #define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_VAR_NOINIT_8
    #undef NVM_START_SEC_VAR_NOINIT_8
    #define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef NVM_STOP_SEC_VAR_NOINIT_8
    #undef NVM_STOP_SEC_VAR_NOINIT_8
    #define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_NOINIT_UNSPECIFIED
    #undef NVM_START_SEC_VAR_NOINIT_UNSPECIFIED
    #define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
    #undef NVM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_UNSPECIFIED
    #undef NVM_START_SEC_VAR_UNSPECIFIED
    #define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_VAR_UNSPECIFIED
    #undef NVM_STOP_SEC_VAR_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_FAST_8
    #undef NVM_START_SEC_VAR_FAST_8
    #define START_SEC_VAR_FAST_NOINIT_8BIT
#endif
#ifdef NVM_STOP_SEC_VAR_FAST_8
    #undef NVM_STOP_SEC_VAR_FAST_8
    #define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef NVM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef NVM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#if defined(VSTDLIB_START_SEC_CODE)
# undef VSTDLIB_START_SEC_CODE
# define START_SEC_CODE
#endif
#if defined(VSTDLIB_STOP_SEC_CODE)
# undef VSTDLIB_STOP_SEC_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_PUBLIC_CODE)
# undef FLS_START_SEC_PUBLIC_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_PUBLIC_CODE)
# undef FLS_STOP_SEC_PUBLIC_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_SCHEDULER_CODE)
# undef FLS_START_SEC_SCHEDULER_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_SCHEDULER_CODE)
# undef FLS_STOP_SEC_SCHEDULER_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_PRIVATE_CODE)
# undef FLS_START_SEC_PRIVATE_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_PRIVATE_CODE)
# undef FLS_STOP_SEC_PRIVATE_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_CODE_FAST)
# undef FLS_START_SEC_CODE_FAST
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_CODE_FAST)
# undef FLS_STOP_SEC_CODE_FAST
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_BUFFER_CODE)
# undef FLS_START_SEC_BUFFER_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_BUFFER_CODE)
# undef FLS_STOP_SEC_BUFFER_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_APPL_CODE)
# undef FLS_START_SEC_APPL_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_APPL_CODE)
# undef FLS_STOP_SEC_APPL_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_VAR_NOINIT_UNSPECIFIED)
# undef FLS_START_SEC_VAR_NOINIT_UNSPECIFIED
# define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
# undef FLS_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_UNSPECIFIED)
# undef FLS_START_SEC_VAR_UNSPECIFIED
# define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_VAR_UNSPECIFIED)
# undef FLS_STOP_SEC_VAR_UNSPECIFIED
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_BOOLEAN)
# undef FLS_START_SEC_VAR_BOOLEAN
# define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_VAR_BOOLEAN)
# undef FLS_STOP_SEC_VAR_BOOLEAN
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_1BIT)
# undef FLS_START_SEC_VAR_1BIT
# define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_VAR_1BIT)
# undef FLS_STOP_SEC_VAR_1BIT
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_NOINIT_32)
# undef FLS_START_SEC_VAR_NOINIT_32
# define START_SEC_VAR_NOINIT_32BIT
#endif
#if defined(FLS_STOP_SEC_VAR_NOINIT_32)
# undef FLS_STOP_SEC_VAR_NOINIT_32
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_NOINIT_32BIT)
# undef FLS_START_SEC_VAR_NOINIT_32BIT
# define START_SEC_VAR_NOINIT_32BIT
#endif
#if defined(FLS_STOP_SEC_VAR_NOINIT_32BIT)
# undef FLS_STOP_SEC_VAR_NOINIT_32BIT
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_DBTOC_DATA_UNSPECIFIED)
# undef FLS_START_SEC_DBTOC_DATA_UNSPECIFIED
# define START_SEC_CONST_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_DBTOC_DATA_UNSPECIFIED)
# undef FLS_STOP_SEC_DBTOC_DATA_UNSPECIFIED
# define STOP_SEC_CONST
#endif

#if defined(FDL_START_SEC_PUBLIC_CODE)
# undef FDL_START_SEC_PUBLIC_CODE
# define START_SEC_CODE
#endif
#if defined(FDL_STOP_SEC_PUBLIC_CODE)
# undef FDL_STOP_SEC_PUBLIC_CODE
# define STOP_SEC_CODE
#endif

#if defined(FDL_START_SEC_CONST_UNSPECIFIED)
    #undef FDL_START_SEC_CONST_UNSPECIFIED
    #define START_SEC_CONST_UNSPECIFIED
#endif
#if defined(FDL_STOP_SEC_CONST_UNSPECIFIED)
    #undef FDL_STOP_SEC_CONST_UNSPECIFIED
    #define STOP_SEC_CONST
#endif

#if defined(FDL_START_SEC_VAR_UNSPECIFIED)
# undef FDL_START_SEC_VAR_UNSPECIFIED
# define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#if defined(FDL_STOP_SEC_VAR_UNSPECIFIED)
# undef FDL_STOP_SEC_VAR_UNSPECIFIED
# define STOP_SEC_VAR
#endif

#if defined(CRC_START_SEC_CODE)
# undef CRC_START_SEC_CODE
# define START_SEC_CODE
#endif
#if defined(CRC_STOP_SEC_CODE)
# undef CRC_STOP_SEC_CODE
# define STOP_SEC_CODE
#endif

#ifdef CRC_START_SEC_CONST_8BIT
    #undef CRC_START_SEC_CONST_8BIT
    #define START_SEC_CONST_8BIT
#endif
#ifdef CRC_STOP_SEC_CONST_8BIT
    #undef CRC_STOP_SEC_CONST_8BIT
    #define STOP_SEC_CONST
#endif

#ifdef CRC_START_SEC_CONST_16BIT
    #undef CRC_START_SEC_CONST_16BIT
    #define START_SEC_CONST_16BIT
#endif
#ifdef CRC_STOP_SEC_CONST_16BIT
    #undef CRC_STOP_SEC_CONST_16BIT
    #define STOP_SEC_CONST
#endif

#ifdef CRC_START_SEC_CONST_32BIT
    #undef CRC_START_SEC_CONST_32BIT
    #define START_SEC_CONST_32BIT
#endif
#ifdef CRC_STOP_SEC_CONST_32BIT
    #undef CRC_STOP_SEC_CONST_32BIT
    #define STOP_SEC_CONST
#endif

 #if defined(CANTRCV_30_TJA1043_START_SEC_CODE)
# undef CANTRCV_30_TJA1043_START_SEC_CODE
# define START_SEC_CODE
#endif
#if defined(CANTRCV_30_TJA1043_STOP_SEC_CODE)
# undef CANTRCV_30_TJA1043_STOP_SEC_CODE
# define STOP_SEC_CODE
#endif

#if defined(CANTRCV_30_TJA1043_START_SEC_CONST_UNSPECIFIED)
    #undef CANTRCV_30_TJA1043_START_SEC_CONST_UNSPECIFIED
    #define START_SEC_CONST_UNSPECIFIED
#endif
#if defined(CANTRCV_30_TJA1043_STOP_SEC_CONST_UNSPECIFIED)
    #undef CANTRCV_30_TJA1043_STOP_SEC_CONST_UNSPECIFIED
    #define STOP_SEC_CONST
#endif

#if defined(CANTRCV_30_TJA1043_START_SEC_VAR_NOINIT_UNSPECIFIED)
# undef CANTRCV_30_TJA1043_START_SEC_VAR_NOINIT_UNSPECIFIED
# define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#if defined(CANTRCV_30_TJA1043_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
# undef CANTRCV_30_TJA1043_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# define STOP_SEC_VAR
#endif

#ifdef COMM_START_SEC_CODE
# undef COMM_START_SEC_CODE
# define START_SEC_CODE
#endif
#ifdef COMM_STOP_SEC_CODE
# undef COMM_STOP_SEC_CODE
# define STOP_SEC_CODE
#endif

#ifdef COMM_START_SEC_CONFIG_DATA_8
#undef COMM_START_SEC_CONFIG_DATA_8
#define START_SEC_CONST_8BIT
#endif
#ifdef COMM_STOP_SEC_CONFIG_DATA_8
#undef COMM_STOP_SEC_CONFIG_DATA_8
#define STOP_SEC_CONST
#endif

#ifdef COMM_START_SEC_CONFIG_DATA_16
#undef COMM_START_SEC_CONFIG_DATA_16
#define START_SEC_CONST_16BIT
#endif
#ifdef COMM_STOP_SEC_CONFIG_DATA_16
#undef COMM_STOP_SEC_CONFIG_DATA_16
#define STOP_SEC_CONST
#endif

#ifdef COMM_START_SEC_CONST_UNSPECIFIED
#undef COMM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef COMM_STOP_SEC_CONST_UNSPECIFIED
#undef COMM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef COMM_START_SEC_CONFIG_DATA_UNSPECIFIED
#undef COMM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef COMM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#undef COMM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef COMM_START_SEC_VAR_CLEARED_UNSPECIFIED
#undef COMM_START_SEC_VAR_CLEARED_UNSPECIFIED
#define START_SEC_VAR_CLEARED_UNSPECIFIED
#endif
#ifdef COMM_STOP_SEC_VAR_CLEARED_UNSPECIFIED
#undef COMM_STOP_SEC_VAR_CLEARED_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#include "MemMap_Common.h"

