

#ifndef DEM_APP_INTERFACE_X_H
#define DEM_APP_INTERFACE_X_H

#include "types.h"
#include "Rte_Dem_Type.h"
#include "Dem_EnvDataElement.h"

#define cPART_IS_FLASHED          0xff
#define cPART_PASSED_BHSENS_EOL   0xaa
#define cPART_HAD_FIRST_STARTUP   0x55
#define cPART_PASSED_LMC_EOL      0x66

extern void Dem_SetCurrentTirePressures(uint8 ucFL, uint8 ucFR, uint8 ucRL, uint8 ucRR);
extern void Dem_SetCurrentTireTemperatures(uint8 ucFL, uint8 ucFR, uint8 ucRL, uint8 ucRR);
extern void Dem_SetCurrentLearnLocateStatus(uint8 ucLLStatus);
extern void Dem_SetCurrentMileage(uint32 ulMileage);

extern Dem_ReadExternalDataElementFnc Dem_GetData_VehicleSpeed(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_Reserved(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_LVBatteryVoltage(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_VehicleMode(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_Mileage(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_AmbientTemperature(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_OccDate(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_OccTime(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_TirePressures(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_TireTemperatures(uint8* ucBuffer);
extern Dem_ReadExternalDataElementFnc Dem_GetData_EcuMode_LLStatus(uint8* ucBuffer);

extern Std_ReturnType Dcm_DemGetSRData_SR_EDR_Record_ExtendedDataRecord0x01_DTCExtendedDataRecordData(uint8* ucExtendedRecordData);

extern Std_ReturnType DemEvent_ModuleNotProvisioned_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_BatteryVoltageLow_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_BatteryVoltageHigh_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_FailedMemory_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);

extern Std_ReturnType DemEvent_CanAbsWheelPulseSignalMissing_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_CanBcmPowerModeSignalMissing_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_CanAtmosphericTemperatureSignalMissing_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_CanBusoffError_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_CanClockSyncSignalMissing_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_CanWheelDirectionSignalMissing_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_CanSpeedSignalMissing_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);

extern Std_ReturnType DemEvent_TpmsNotFunctional_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_AutolocationFail_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_EcuRfInterference_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_NoQualifiedSensorSignals_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_DetectedTooManySensors_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);

extern Std_ReturnType DemEvent_SensorDefectFL_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorDefectFR_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorDefectRL_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorDefectRR_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorDefectUnknownPosition_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);

extern Std_ReturnType DemEvent_SensorLifeTimeCounterLowFL_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorLifeTimeCounterLowFR_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorLifeTimeCounterLowRL_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorLifeTimeCounterLowRR_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);

extern Std_ReturnType DemEvent_SensorMissingFL_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorMissingFR_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorMissingRL_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorMissingRR_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorMissingUnknownPosition_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);

extern Std_ReturnType DemEvent_SensorOvertempFL_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorOvertempFR_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorOvertempRL_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);
extern Std_ReturnType DemEvent_SensorOvertempRR_InitMonForEvent(Dem_InitMonitorReasonType InitMonitorReason);

extern Std_ReturnType DemEvent_LowBatteryVoltageLow_EventDataChanged(Dem_EventIdType EventId);
extern Std_ReturnType Dem_CallbackDtcStatusChanged(uint32 DTC, Dem_UdsStatusByteType DTCStatusOld, Dem_UdsStatusByteType DTCStatusNew);
#endif

