#pragma once
/******************************************************************************/
/* File   : Dem_Cfg_Deb.hpp                                                   */
/*                                                                            */
/* Author : Raajnaag HULIYAPURADA MATA                                        */
/*                                                                            */
/* License / Warranty / Terms and Conditions                                  */
/*                                                                            */
/* Everyone is permitted to copy and distribute verbatim copies of this lice- */
/* nse document, but changing it is not allowed. This is a free, copyright l- */
/* icense for software and other kinds of works. By contrast, this license is */
/* intended to guarantee your freedom to share and change all versions of a   */
/* program, to make sure it remains free software for all its users. You have */
/* certain responsibilities, if you distribute copies of the software, or if  */
/* you modify it: responsibilities to respect the freedom of others.          */
/*                                                                            */
/* All rights reserved. Copyright © 1982 Raajnaag HULIYAPURADA MATA           */
/*                                                                            */
/* Always refer latest software version from:                                 */
/* https://github.com/RaajnaagHuliyapuradaMata?tab=repositories               */
/*                                                                            */
/******************************************************************************/

/******************************************************************************/
/* #INCLUDES                                                                  */
/******************************************************************************/

/******************************************************************************/
/* #DEFINES                                                                   */
/******************************************************************************/
#define DEM_CFG_DEBMONINTERNAL_OFF  STD_OFF
#define DEM_CFG_DEBMONINTERNAL_ON   STD_ON
#define DEM_CFG_DEBMONINTERNAL  DEM_CFG_DEBMONINTERNAL_OFF
#define DEM_CFG_DEBARTIMEBASE_OFF  STD_OFF
#define DEM_CFG_DEBARTIMEBASE_ON   STD_ON
#define DEM_CFG_DEBARTIMEBASE  DEM_CFG_DEBARTIMEBASE_ON
#define DEM_CFG_DEBARTIME_PARAMSET1_LENGTH 1

#define DEM_CFG_DEBARTIME_PARAMSET1 { \
 \
   { 500, -500, 500, DEM_MAXSINT16},  \
}

#define DEM_DEBPARAM_IDX_EVENT_NOECUSERIALNUMBER        0u
#define DEM_CFG_DEBCOUNTERBASECLASS_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS  DEM_CFG_DEBCOUNTERBASECLASS_ON
#define DEM_CFG_LIMIT_RELEVANTFOR_JUMPING_OFF  STD_OFF
#define DEM_CFG_LIMIT_RELEVANTFOR_JUMPING_ON   STD_ON
#define DEM_CFG_LIMIT_RELEVANTFOR_JUMPING DEM_CFG_LIMIT_RELEVANTFOR_JUMPING_OFF
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT 32767
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MINLIMIT -32768
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPUP_ENABLED TRUE
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPUP_VALUE 0
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPDOWN_ENABLED TRUE
#define DEM_CFG_DEFAULT_DEBCOUNTERCLASS_JUMPDOWN_VALUE 0
#define DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD  DEM_CFG_DEBCOUNTERBASECLASS_MINTHRESHOLD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD  DEM_CFG_DEBCOUNTERBASECLASS_MAXTHRESHOLD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE  DEM_CFG_DEBCOUNTERBASECLASS_JUMPUPVALUE_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE  DEM_CFG_DEBCOUNTERBASECLASS_JUMPDOWNVALUE_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN  DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPDOWN_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP_OFF  STD_OFF
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP_ON   STD_ON
#define DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP  DEM_CFG_DEBCOUNTERBASECLASS_ISJUMPUP_ON

#define DEMRB_DEBOUNCECOUNTERSETS_SIZE                                 2
#define DEMRB_DEBOUNCECOUNTERSETS_CUSTOMSETSOFFSET                     2
#define DemConf_DemRbDebounceCounterSet_Standard                       0
#define DemConf_DemRbDebounceCounterSet_Alternative                    1
#define DEM_CFG_DEBCOUNTERBASECLASS_PARAMSET_LENGTH 1
#define DEM_CFG_ALTERNATIVEDEBDEFINED                    FALSE

#define DEM_CFG_DEBCOUNTERCLASS_PARAMSETS { \
  {  \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,     FALSE,     -15,     15,     0,     0,     DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
}, \
  {   \
   DEM_DEBCOUNTERBASECLASS_INIT (TRUE,     FALSE,     -15,     15,     0,     0,     DEM_CFG_DEFAULT_DEBCOUNTERCLASS_MAXLIMIT,DEM_MAXSINT16,1,   -1                  ), \
  }, \
}

#define DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1  0u
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_AUTOLOCATIONFAIL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANABSWHEELPULSESIGNALMISSING  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANATMOSPHERICTEMPERATURESIGNALMISSING  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANBUSOFFERROR  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANCLOCKSYNCSIGNALMISSING  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANOFFROADSIGNALMISSING  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANSPEEDSIGNALMISSING  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANVEHICLEMODESIGNALMISSING  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANWHEELDIRECTIONSIGNALMISSING  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHAMP  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHBCM  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHDCMFL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHDCMRL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHSCMFL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_DETECTEDTOOMANYSENSORS  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_ECURFINTERFERENCE  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_NOQUALIFIEDSENSORSIGNALS  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTFL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTFR  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTRL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTRR  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTUNKNOWNPOSITION  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORLIFETIMECOUNTERLOWFL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORLIFETIMECOUNTERLOWFR  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORLIFETIMECOUNTERLOWRL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORLIFETIMECOUNTERLOWRR  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGFL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGFR  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGRL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGRR  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGUNKNOWNPOSITION  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSOROVERTEMPFL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSOROVERTEMPFR  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSOROVERTEMPRL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSOROVERTEMPRR  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_TPMSNOTFUNCTIONAL  DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_EVENT_BATTERYVOLTAGEHIGH       DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_EVENT_BATTERYVOLTAGELOW        DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_EVENT_FAILEDMEMORY             DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1
#define DEM_DEBPARAM_IDX_EVENT_NOVIN                    DEM_DEBPARAMCLASS_IDX_DEMDEBOUNCECOUNTERBASEDCLASS_1

#define DEM_CFG_DEB_DEFINE_ALL_PARAMSETS \
static const Dem_DebArTime_ParamSet    Dem_Cfg_DebArTime_Paramset1[DEM_CFG_DEBARTIME_PARAMSET1_LENGTH] = DEM_CFG_DEBARTIME_PARAMSET1; \
static const Dem_DebCounterBaseClass_ParamSet  Dem_Cfg_DebCounterBaseClass_Paramsets[DEMRB_DEBOUNCECOUNTERSETS_SIZE][DEM_CFG_DEBCOUNTERBASECLASS_PARAMSET_LENGTH] = DEM_CFG_DEBCOUNTERCLASS_PARAMSETS; \

#define DEM_CFG_DEB_CLASSES { \
   { \
      NULL_PTR, \
      NULL_PTR, \
      NULL_PTR, \
      0, \
      NULL_PTR \
   }\
   ,{ \
      &Dem_DebArTime_GetLimits, \
      &Dem_DebArTime_Cyclic, \
      &Dem_Cfg_DebArTime_Paramset1, \
      DEM_CFG_DEBARTIME_PARAMSET1_LENGTH, \
      &Dem_DebArTime_Filter \
   }\
   ,{ \
      &Dem_DebCounterBaseClass_GetLimits, \
      NULL_PTR, \
      &Dem_Cfg_DebCounterBaseClass_Paramsets[DemConf_DemRbDebounceCounterSet_Standard], \
      DEM_CFG_DEBCOUNTERBASECLASS_PARAMSET_LENGTH, \
      &Dem_DebCounterBaseClass_Filter \
   }\
}

#define DEM_CFG_DEB_NUMBEROFCLASSES  3
#define DEM_DEBMETH_IDX_ARTIME      (1u)
#define DEM_DEBMETH_IDX_ARCTRBASECLASS      (2u)
#define DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO_OFF                                    0u
#define DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO_ACCORDING_DEBOUNCEBEHAVIOR             1u
#define DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO           DEM_CFG_SUPPORT_DEB_RESET_AFTER_STOCO_OFF

/******************************************************************************/
/* MACROS                                                                     */
/******************************************************************************/

/******************************************************************************/
/* TYPEDEFS                                                                   */
/******************************************************************************/

/******************************************************************************/
/* CONSTS                                                                     */
/******************************************************************************/

/******************************************************************************/
/* PARAMS                                                                     */
/******************************************************************************/

/******************************************************************************/
/* OBJECTS                                                                    */
/******************************************************************************/

/******************************************************************************/
/* FUNCTIONS                                                                  */
/******************************************************************************/

/******************************************************************************/
/* EOF                                                                        */
/******************************************************************************/

