

#ifndef DEM_CFG_ENVDATAELEMENT_DATASIZE_H
#define DEM_CFG_ENVDATAELEMENT_DATASIZE_H

#include "Std_Types.h"
#include "Dcm_Dem.h"

#define DEM_CFG_ENV_DATAELEMENTS_EXTERN_AVAILABILITY   STD_ON
#define DEM_CFG_ENV_DATAELEMENTS_INTERN_AVAILABILITY  STD_OFF

#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_VEHICLESPEED  2
#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_AMBIENTTEMPERATURE  1
#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_VEHICLEMODE  1
#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_RESERVED  2
#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_LVBATTERYVOLTAGE  1
#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_OCCDATE  8
#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_OCCTIME  8
#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_TIREPRESSURES  4
#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_TIRETEMPERATURES  4
#define DataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_ECUMODE_LLSTATUS  1
#define DataSize_DEM_DATAELEM_SR_EDR_RECORD_EXTENDEDDATARECORD0X01_DTCEXTENDEDDATARECORDDATA  1

#endif

