

#ifndef DEM_CFG_ENVFREEZEFRAME_H
#define DEM_CFG_ENVFREEZEFRAME_H

#define DEM_CFG_ENVFREEZEFRAME2DID \
{ \
   DEM_DID_DEMDIDCLASS_0XFFF,  \
   DEM_DID_DEMDIDCLASS_POWERMODE_B000,   DEM_DID_DEMDIDCLASS_RESERVED_B004,   DEM_DID_DEMDIDCLASS_SUPPLYVOLTAGE_B001,   DEM_DID_DEMDIDCLASS_VEHICLESPEED_B002,   DEM_DID_DEMDIDCLASS_AMBIENTTEMPERATURE_B003,   DEM_DID_DEMDIDCLASS_ECUMODE_LLSTATUS_B009,   DEM_DID_DEMDIDCLASS_OCCDATE_B005,   DEM_DID_DEMDIDCLASS_OCCTIME_B006,   DEM_DID_DEMDIDCLASS_TIREPRESSURES_B007,   DEM_DID_DEMDIDCLASS_TIRETEMPERATURES_B008,  \
   0 \
}

#define DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS         1
#define DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_TPMS         2

#define DEM_CFG_ENVFREEZEFRAME \
{ \
   { 0,0 } \
   ,{ 1, 1 }     \
   ,{ 11, 32 }     \
}

#define DEM_CFG_ENVFREEZEFRAME_ARRAYLENGTH  (2+1)

#endif

