/******************************************************************************/
/* File   : Dem_Cfg_Events_DataStructures.c                                   */
/*                                                                            */
/* Author : Raajnaag HULIYAPURADA MATA                                        */
/*                                                                            */
/* License / Warranty / Terms and Conditions                                  */
/*                                                                            */
/* Everyone is permitted to copy and distribute verbatim copies of this lice- */
/* nse document, but changing it is not allowed. This is a free, copyright l- */
/* icense for software and other kinds of works. By contrast, this license is */
/* intended to guarantee your freedom to share and change all versions of a   */
/* program, to make sure it remains free software for all its users. You have */
/* certain responsibilities, if you distribute copies of the software, or if  */
/* you modify it: responsibilities to respect the freedom of others.          */
/*                                                                            */
/* All rights reserved. Copyright © 1982 Raajnaag HULIYAPURADA MATA           */
/*                                                                            */
/* Always refer latest software version from:                                 */
/* https://github.com/RaajnaagHuliyapuradaMata?tab=repositories               */
/*                                                                            */
/******************************************************************************/

/******************************************************************************/
/* #INCLUDES                                                                  */
/******************************************************************************/
#include "Std_Types.hpp"

#include "Dem_Cfg_Events_DataStructures.hpp"
#include "Dem_Cfg_EventsCallback.hpp"
#include "DemAppInterfaceX.hpp"
#include "Rte_Dem.hpp"
#include "FiM.hpp"
#include "Rte_Dem.hpp"

/******************************************************************************/
/* #DEFINES                                                                   */
/******************************************************************************/

/******************************************************************************/
/* MACROS                                                                     */
/******************************************************************************/

/******************************************************************************/
/* TYPEDEFS                                                                   */
/******************************************************************************/

/******************************************************************************/
/* CONSTS                                                                     */
/******************************************************************************/
const Dem_EvtParam_32Type Dem_EvtParam_32[42] = {
   { 0 },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_AUTOLOCATIONFAIL&0x3Fu) << 10) + ( (uint32)(7u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANABSWHEELPULSESIGNALMISSING&0x3Fu) << 10) + ( (uint32)(4u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANATMOSPHERICTEMPERATURESIGNALMISSING&0x3Fu) << 10) + ( (uint32)(4u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANBUSOFFERROR&0x3Fu) << 10) + ( (uint32)(1u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANCLOCKSYNCSIGNALMISSING&0x3Fu) << 10) + ( (uint32)(2u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANOFFROADSIGNALMISSING&0x3Fu) << 10) + ( (uint32)(4u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANSPEEDSIGNALMISSING&0x3Fu) << 10) + ( (uint32)(4u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANVEHICLEMODESIGNALMISSING&0x3Fu) << 10) + ( (uint32)(4u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_CANWHEELDIRECTIONSIGNALMISSING&0x3Fu) << 10) + ( (uint32)(2u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHAMP&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHBCM&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHDCMFL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHDCMRL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_BUSACTIVE&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_COMMUNICATIONERRORWITHSCMFL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_DETECTEDTOOMANYSENSORS&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_ECURFINTERFERENCE&0x3Fu) << 10) + ( (uint32)(5u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_NOQUALIFIEDSENSORSIGNALS&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTFL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTFR&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTRL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTRR&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORDEFECTUNKNOWNPOSITION&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORLIFETIMECOUNTERLOWFL&0x3Fu) << 10) + ( (uint32)(5u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORLIFETIMECOUNTERLOWFR&0x3Fu) << 10) + ( (uint32)(5u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORLIFETIMECOUNTERLOWRL&0x3Fu) << 10) + ( (uint32)(5u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORLIFETIMECOUNTERLOWRR&0x3Fu) << 10) + ( (uint32)(5u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGFL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGFR&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGRL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGRR&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSORMISSINGUNKNOWNPOSITION&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(0uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSOROVERTEMPFL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(0uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSOROVERTEMPFR&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(0uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSOROVERTEMPRL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(0uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_IGNITION&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_SENSOROVERTEMPRR&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_DEMEVENTPARAMETER_TPMSNOTFUNCTIONAL&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_EVENT_BATTERYVOLTAGEHIGH&0x3Fu) << 10) + ( (uint32)(2u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(1u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_EVENT_BATTERYVOLTAGELOW&0x3Fu) << 10) + ( (uint32)(2u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_EVENT_FAILEDMEMORY&0x3Fu) << 10) + ( (uint32)(3u&0x7u) << 16) + ( (uint32)(1u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARTIME&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_EVENT_NOECUSERIALNUMBER&0x3Fu) << 10) + ( (uint32)(4u&0x7u) << 16) + ( (uint32)(0u&0x1u) << 19) },
   { ( (uint32)(0u&0x1u) << 0) + ( (uint32)(1uL&0x1u) << 1) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 2) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 4) + ( (uint32)(DemConf_DemOperationCycle_DemOperationCycle_POWER&0x3u) << 6) + ( (uint32)(DEM_DEBMETH_IDX_ARCTRBASECLASS&0x3u) << 8) + ( (uint32)(DEM_DEBPARAM_IDX_EVENT_NOVIN&0x3Fu) << 10) + ( (uint32)(4u&0x7u) << 16) + ( (uint32)(0u&0x1u) << 19) }
};

/******************************************************************************/
/* PARAMS                                                                     */
/******************************************************************************/

/******************************************************************************/
/* OBJECTS                                                                    */
/******************************************************************************/

/******************************************************************************/
/* FUNCTIONS                                                                  */
/******************************************************************************/

/******************************************************************************/
/* EOF                                                                        */
/******************************************************************************/

