

#if defined (NOT_DEFINED)

#elif defined (OS_START_SEC_VAR_TRACE)
  #undef      OS_START_SEC_VAR_TRACE
#define DEFAULT_START_SEC_VAR_NO_INIT_UNSPECIFIED
#elif defined (OS_STOP_SEC_VAR_TRACE)
  #undef      OS_STOP_SEC_VAR_TRACE
#define DEFAULT_STOP_SEC_VAR_NO_INIT_UNSPECIFIED

#elif defined (OS_START_SEC_VAR_NO_INIT_UNSPECIFIED)
  #undef      OS_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define DEFAULT_START_SEC_VAR_NO_INIT_UNSPECIFIED
#elif defined (OS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
  #undef      OS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define DEFAULT_STOP_SEC_VAR_NO_INIT_UNSPECIFIED

#elif defined (OS_START_SEC_VAR_CLEARED_UNSPECIFIED)
  #undef      OS_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DEFAULT_START_SEC_VAR_CLEARED_UNSPECIFIED
#elif defined (OS_STOP_SEC_VAR_CLEARED_UNSPECIFIED)
  #undef      OS_STOP_SEC_VAR_CLEARED_UNSPECIFIED
#define DEFAULT_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined (OS_START_SEC_CONST_FAST_UNSPECIFIED)
  #undef      OS_START_SEC_CONST_FAST_UNSPECIFIED
#define DEFAULT_START_SEC_CONST_FAST_UNSPECIFIED
#elif defined (OS_STOP_SEC_CONST_FAST_UNSPECIFIED)
  #undef      OS_STOP_SEC_CONST_FAST_UNSPECIFIED
#define DEFAULT_STOP_SEC_CONST_FAST_UNSPECIFIED

#elif defined (OS_START_SEC_CONST_UNSPECIFIED)
  #undef      OS_START_SEC_CONST_UNSPECIFIED
#define DEFAULT_START_SEC_CONST_UNSPECIFIED
#elif defined (OS_STOP_SEC_CONST_UNSPECIFIED)
  #undef      OS_STOP_SEC_CONST_UNSPECIFIED
#define DEFAULT_STOP_SEC_CONST_UNSPECIFIED

#elif defined (OS_START_SEC_APPL_CODE)
  #undef      OS_START_SEC_APPL_CODE
#define DEFAULT_START_SEC_APPL_CODE
#elif defined (OS_STOP_SEC_APPL_CODE)
  #undef      OS_STOP_SEC_APPL_CODE
#define DEFAULT_STOP_SEC_APPL_CODE

#elif defined (OS_START_SEC_CALLOUT_CODE)
  #undef      OS_START_SEC_CALLOUT_CODE
#define DEFAULT_START_SEC_CALLOUT_CODE
#elif defined (OS_STOP_SEC_CALLOUT_CODE)
  #undef      OS_STOP_SEC_CALLOUT_CODE
#define DEFAULT_STOP_SEC_CALLOUT_CODE

#elif defined (OS_START_SEC_CODE_FAST)
  #undef      OS_START_SEC_CODE_FAST
#define DEFAULT_START_SEC_CODE_FAST
#elif defined (OS_STOP_SEC_CODE_FAST)
  #undef      OS_STOP_SEC_CODE_FAST
#define DEFAULT_STOP_SEC_CODE_FAST

#elif defined (OS_START_SEC_CODE_LIB)
  #undef      OS_START_SEC_CODE_LIB
#define DEFAULT_START_SEC_CODE_LIB
#elif defined (OS_STOP_SEC_CODE_LIB)
  #undef      OS_STOP_SEC_CODE_LIB
#define DEFAULT_STOP_SEC_CODE_LIB

#elif defined (OS_START_SEC_VECTORS)
  #undef      OS_START_SEC_VECTORS
#define DEFAULT_START_SEC_VECTORS
#elif defined (OS_STOP_SEC_VECTORS)
  #undef      OS_STOP_SEC_VECTORS
#define DEFAULT_STOP_SEC_VECTORS

#elif defined (OS_START_SEC_STARTUPHOOK_HUFTPMS_CODE)
  #undef      OS_START_SEC_STARTUPHOOK_HUFTPMS_CODE
#elif defined (OS_STOP_SEC_STARTUPHOOK_HUFTPMS_CODE)
  #undef      OS_STOP_SEC_STARTUPHOOK_HUFTPMS_CODE

#elif defined (OS_START_SEC_SHUTDOWNHOOK_HUFTPMS_CODE)
  #undef      OS_START_SEC_SHUTDOWNHOOK_HUFTPMS_CODE
#elif defined (OS_STOP_SEC_SHUTDOWNHOOK_HUFTPMS_CODE)
  #undef      OS_STOP_SEC_SHUTDOWNHOOK_HUFTPMS_CODE

#elif defined (OS_START_SEC_ERRORHOOK_HUFTPMS_CODE)
  #undef      OS_START_SEC_ERRORHOOK_HUFTPMS_CODE
#elif defined (OS_STOP_SEC_ERRORHOOK_HUFTPMS_CODE)
  #undef      OS_STOP_SEC_ERRORHOOK_HUFTPMS_CODE

#elif defined (OS_START_SEC_OS_CBK_ALARM_CB_ALARM10MS_CODE)
  #undef      OS_START_SEC_OS_CBK_ALARM_CB_ALARM10MS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_ALARM_CB_ALARM10MS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_ALARM_CB_ALARM10MS_CODE

#elif defined (OS_START_SEC_OS_CBK_ALARM_CB_ALARMONESECOND_CODE)
  #undef      OS_START_SEC_OS_CBK_ALARM_CB_ALARMONESECOND_CODE
#elif defined (OS_STOP_SEC_OS_CBK_ALARM_CB_ALARMONESECOND_CODE)
  #undef      OS_STOP_SEC_OS_CBK_ALARM_CB_ALARMONESECOND_CODE

#elif defined (OS_START_SEC_OS_CBK_ALARM_CB_ALARM200MS_CODE)
  #undef      OS_START_SEC_OS_CBK_ALARM_CB_ALARM200MS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_ALARM_CB_ALARM200MS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_ALARM_CB_ALARM200MS_CODE

#elif defined (OS_START_SEC_OS_CBK_ALARM_CB_ALARM50MS_CODE)
  #undef      OS_START_SEC_OS_CBK_ALARM_CB_ALARM50MS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_ALARM_CB_ALARM50MS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_ALARM_CB_ALARM50MS_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER0_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER0_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER0_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER0_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER1_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER1_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER1_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER1_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER2_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER2_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER2_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER2_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER3_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER3_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER3_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TIMER3_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_VOLTAGEMONITOR_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_VOLTAGEMONITOR_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_VOLTAGEMONITOR_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_VOLTAGEMONITOR_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_WAKEUP_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_WAKEUP_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_WAKEUP_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_WAKEUP_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0STATUS_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0STATUS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0STATUS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0STATUS_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_CANGLOBALSTATUS_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_CANGLOBALSTATUS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_CANGLOBALSTATUS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_CANGLOBALSTATUS_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0TRANSMIT_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0TRANSMIT_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0TRANSMIT_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0TRANSMIT_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0RECEIVE_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0RECEIVE_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0RECEIVE_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_CAN0RECEIVE_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_FLS_FLENDNM_CAT2_ISR_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_FLS_FLENDNM_CAT2_ISR_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_FLS_FLENDNM_CAT2_ISR_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_FLS_FLENDNM_CAT2_ISR_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_ONEMILLISECOND_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_ONEMILLISECOND_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_ONEMILLISECOND_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_ONEMILLISECOND_CODE

#elif defined (OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TELREC_CODE)
  #undef      OS_START_SEC_OS_CBK_TERMINATED_CAT2ISR_TELREC_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TELREC_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TERMINATED_CAT2ISR_TELREC_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER0_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER0_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER0_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER0_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER1_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER1_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER1_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER1_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER2_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER2_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER2_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER2_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER3_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER3_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER3_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TIMER3_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_VOLTAGEMONITOR_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_VOLTAGEMONITOR_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_VOLTAGEMONITOR_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_VOLTAGEMONITOR_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_WAKEUP_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_WAKEUP_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_WAKEUP_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_WAKEUP_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0STATUS_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0STATUS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0STATUS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0STATUS_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_CANGLOBALSTATUS_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_CANGLOBALSTATUS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_CANGLOBALSTATUS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_CANGLOBALSTATUS_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0TRANSMIT_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0TRANSMIT_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0TRANSMIT_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0TRANSMIT_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0RECEIVE_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0RECEIVE_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0RECEIVE_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_CAN0RECEIVE_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_FLS_FLENDNM_CAT2_ISR_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_FLS_FLENDNM_CAT2_ISR_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_FLS_FLENDNM_CAT2_ISR_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_FLS_FLENDNM_CAT2_ISR_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_ONEMILLISECOND_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_ONEMILLISECOND_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_ONEMILLISECOND_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_ONEMILLISECOND_CODE

#elif defined (OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TELREC_CODE)
  #undef      OS_START_SEC_OS_CBK_DISABLE_CAT2ISR_TELREC_CODE
#elif defined (OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TELREC_CODE)
  #undef      OS_STOP_SEC_OS_CBK_DISABLE_CAT2ISR_TELREC_CODE

#elif defined (OS_START_SEC_ERRORHOOK_CODE)
  #undef      OS_START_SEC_ERRORHOOK_CODE
#elif defined (OS_STOP_SEC_ERRORHOOK_CODE)
  #undef      OS_STOP_SEC_ERRORHOOK_CODE

#elif defined (OS_START_SEC_PRETASKHOOK_CODE)
  #undef      OS_START_SEC_PRETASKHOOK_CODE
#elif defined (OS_STOP_SEC_PRETASKHOOK_CODE)
  #undef      OS_STOP_SEC_PRETASKHOOK_CODE

#elif defined (OS_START_SEC_POSTTASKHOOK_CODE)
  #undef      OS_START_SEC_POSTTASKHOOK_CODE
#elif defined (OS_STOP_SEC_POSTTASKHOOK_CODE)
  #undef      OS_STOP_SEC_POSTTASKHOOK_CODE

#elif defined (OS_START_SEC_PROTECTIONHOOK_CODE)
  #undef      OS_START_SEC_PROTECTIONHOOK_CODE
#elif defined (OS_STOP_SEC_PROTECTIONHOOK_CODE)
  #undef      OS_STOP_SEC_PROTECTIONHOOK_CODE

#elif defined (OS_START_SEC_STARTUPHOOK_CODE)
  #undef      OS_START_SEC_STARTUPHOOK_CODE
#elif defined (OS_STOP_SEC_STARTUPHOOK_CODE)
  #undef      OS_STOP_SEC_STARTUPHOOK_CODE

#elif defined (OS_START_SEC_SHUTDOWNHOOK_CODE)
  #undef      OS_START_SEC_SHUTDOWNHOOK_CODE
#elif defined (OS_STOP_SEC_SHUTDOWNHOOK_CODE)
  #undef      OS_STOP_SEC_SHUTDOWNHOOK_CODE

#elif defined (OS_START_SEC_OS_CBK_CHECKMEMORYACCESS_CODE)
  #undef      OS_START_SEC_OS_CBK_CHECKMEMORYACCESS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_CHECKMEMORYACCESS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_CHECKMEMORYACCESS_CODE

#elif defined (OS_START_SEC_OS_CBK_IDLE_CODE)
  #undef      OS_START_SEC_OS_CBK_IDLE_CODE
#elif defined (OS_STOP_SEC_OS_CBK_IDLE_CODE)
  #undef      OS_STOP_SEC_OS_CBK_IDLE_CODE

#elif defined (OS_START_SEC_OS_CBK_INSHUTDOWN_CODE)
  #undef      OS_START_SEC_OS_CBK_INSHUTDOWN_CODE
#elif defined (OS_STOP_SEC_OS_CBK_INSHUTDOWN_CODE)
  #undef      OS_STOP_SEC_OS_CBK_INSHUTDOWN_CODE

#elif defined (OS_START_SEC_OS_CBK_STACKOVERRUNHOOK_CODE)
  #undef      OS_START_SEC_OS_CBK_STACKOVERRUNHOOK_CODE
#elif defined (OS_STOP_SEC_OS_CBK_STACKOVERRUNHOOK_CODE)
  #undef      OS_STOP_SEC_OS_CBK_STACKOVERRUNHOOK_CODE

#elif defined (OS_START_SEC_OS_CBK_CHECKSTACKDEPTH_CODE)
  #undef      OS_START_SEC_OS_CBK_CHECKSTACKDEPTH_CODE
#elif defined (OS_STOP_SEC_OS_CBK_CHECKSTACKDEPTH_CODE)
  #undef      OS_STOP_SEC_OS_CBK_CHECKSTACKDEPTH_CODE

#elif defined (OS_START_SEC_OS_CBK_GETSTOPWATCH_CODE)
  #undef      OS_START_SEC_OS_CBK_GETSTOPWATCH_CODE
#elif defined (OS_STOP_SEC_OS_CBK_GETSTOPWATCH_CODE)
  #undef      OS_STOP_SEC_OS_CBK_GETSTOPWATCH_CODE

#elif defined (OS_START_SEC_OS_CBK_TIMEOVERRUNHOOK_CODE)
  #undef      OS_START_SEC_OS_CBK_TIMEOVERRUNHOOK_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TIMEOVERRUNHOOK_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TIMEOVERRUNHOOK_CODE

#elif defined (OS_START_SEC_OS_CBK_SUSPENDTIMELIMIT_CODE)
  #undef      OS_START_SEC_OS_CBK_SUSPENDTIMELIMIT_CODE
#elif defined (OS_STOP_SEC_OS_CBK_SUSPENDTIMELIMIT_CODE)
  #undef      OS_STOP_SEC_OS_CBK_SUSPENDTIMELIMIT_CODE

#elif defined (OS_START_SEC_OS_CBK_SETTIMELIMIT_CODE)
  #undef      OS_START_SEC_OS_CBK_SETTIMELIMIT_CODE
#elif defined (OS_STOP_SEC_OS_CBK_SETTIMELIMIT_CODE)
  #undef      OS_STOP_SEC_OS_CBK_SETTIMELIMIT_CODE

#elif defined (OS_START_SEC_OS_CBK_SETMEMORYACCESS_CODE)
  #undef      OS_START_SEC_OS_CBK_SETMEMORYACCESS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_SETMEMORYACCESS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_SETMEMORYACCESS_CODE

#elif defined (OS_START_SEC_OS_CBK_GETSETPROTECTION_CODE)
  #undef      OS_START_SEC_OS_CBK_GETSETPROTECTION_CODE
#elif defined (OS_STOP_SEC_OS_CBK_GETSETPROTECTION_CODE)
  #undef      OS_STOP_SEC_OS_CBK_GETSETPROTECTION_CODE

#elif defined (OS_START_SEC_OS_CBK_TASKSTART_CODE)
  #undef      OS_START_SEC_OS_CBK_TASKSTART_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TASKSTART_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TASKSTART_CODE

#elif defined (OS_START_SEC_OS_CBK_TASKEND_CODE)
  #undef      OS_START_SEC_OS_CBK_TASKEND_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TASKEND_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TASKEND_CODE

#elif defined (OS_START_SEC_OS_CBK_TASKACTIVATED_CODE)
  #undef      OS_START_SEC_OS_CBK_TASKACTIVATED_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TASKACTIVATED_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TASKACTIVATED_CODE

#elif defined (OS_START_SEC_OS_CBK_CROSSCOREISRSTART_CODE)
  #undef      OS_START_SEC_OS_CBK_CROSSCOREISRSTART_CODE
#elif defined (OS_STOP_SEC_OS_CBK_CROSSCOREISRSTART_CODE)
  #undef      OS_STOP_SEC_OS_CBK_CROSSCOREISRSTART_CODE

#elif defined (OS_START_SEC_OS_CBK_CROSSCOREISREND_CODE)
  #undef      OS_START_SEC_OS_CBK_CROSSCOREISREND_CODE
#elif defined (OS_STOP_SEC_OS_CBK_CROSSCOREISREND_CODE)
  #undef      OS_STOP_SEC_OS_CBK_CROSSCOREISREND_CODE

#elif defined (OS_START_SEC_OS_CBK_ISRSTART_CODE)
  #undef      OS_START_SEC_OS_CBK_ISRSTART_CODE
#elif defined (OS_STOP_SEC_OS_CBK_ISRSTART_CODE)
  #undef      OS_STOP_SEC_OS_CBK_ISRSTART_CODE

#elif defined (OS_START_SEC_OS_CBK_ISREND_CODE)
  #undef      OS_START_SEC_OS_CBK_ISREND_CODE
#elif defined (OS_STOP_SEC_OS_CBK_ISREND_CODE)
  #undef      OS_STOP_SEC_OS_CBK_ISREND_CODE

#elif defined (OS_START_SEC_OS_CBK_ISUNTRUSTEDCODEOK_CODE)
  #undef      OS_START_SEC_OS_CBK_ISUNTRUSTEDCODEOK_CODE
#elif defined (OS_STOP_SEC_OS_CBK_ISUNTRUSTEDCODEOK_CODE)
  #undef      OS_STOP_SEC_OS_CBK_ISUNTRUSTEDCODEOK_CODE

#elif defined (OS_START_SEC_OS_CBK_ISUNTRUSTEDTRAPOK_CODE)
  #undef      OS_START_SEC_OS_CBK_ISUNTRUSTEDTRAPOK_CODE
#elif defined (OS_STOP_SEC_OS_CBK_ISUNTRUSTEDTRAPOK_CODE)
  #undef      OS_STOP_SEC_OS_CBK_ISUNTRUSTEDTRAPOK_CODE

#elif defined (OS_START_SEC_OS_CBK_ISSYSTEMTRAPALLOWED_CODE)
  #undef      OS_START_SEC_OS_CBK_ISSYSTEMTRAPALLOWED_CODE
#elif defined (OS_STOP_SEC_OS_CBK_ISSYSTEMTRAPALLOWED_CODE)
  #undef      OS_STOP_SEC_OS_CBK_ISSYSTEMTRAPALLOWED_CODE

#elif defined (OS_START_SEC_OS_CBK_RESTOREGLOBALREGISTERS_CODE)
  #undef      OS_START_SEC_OS_CBK_RESTOREGLOBALREGISTERS_CODE
#elif defined (OS_STOP_SEC_OS_CBK_RESTOREGLOBALREGISTERS_CODE)
  #undef      OS_STOP_SEC_OS_CBK_RESTOREGLOBALREGISTERS_CODE

#elif defined (OS_START_SEC_OS_CBK_TRACECOMMINITTARGET_CODE)
  #undef      OS_START_SEC_OS_CBK_TRACECOMMINITTARGET_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TRACECOMMINITTARGET_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TRACECOMMINITTARGET_CODE

#elif defined (OS_START_SEC_OS_CBK_TRACECOMMDATAREADY_CODE)
  #undef      OS_START_SEC_OS_CBK_TRACECOMMDATAREADY_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TRACECOMMDATAREADY_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TRACECOMMDATAREADY_CODE

#elif defined (OS_START_SEC_OS_CBK_TRACECOMMTXSTART_CODE)
  #undef      OS_START_SEC_OS_CBK_TRACECOMMTXSTART_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TRACECOMMTXSTART_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TRACECOMMTXSTART_CODE

#elif defined (OS_START_SEC_OS_CBK_TRACECOMMTXBYTE_CODE)
  #undef      OS_START_SEC_OS_CBK_TRACECOMMTXBYTE_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TRACECOMMTXBYTE_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TRACECOMMTXBYTE_CODE

#elif defined (OS_START_SEC_OS_CBK_TRACECOMMTXEND_CODE)
  #undef      OS_START_SEC_OS_CBK_TRACECOMMTXEND_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TRACECOMMTXEND_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TRACECOMMTXEND_CODE

#elif defined (OS_START_SEC_OS_CBK_TRACECOMMTXREADY_CODE)
  #undef      OS_START_SEC_OS_CBK_TRACECOMMTXREADY_CODE
#elif defined (OS_STOP_SEC_OS_CBK_TRACECOMMTXREADY_CODE)
  #undef      OS_STOP_SEC_OS_CBK_TRACECOMMTXREADY_CODE

#elif defined (OS_START_SEC_OS_CBK_IDLE_CODE)
  #undef      OS_START_SEC_OS_CBK_IDLE_CODE
#elif defined (OS_STOP_SEC_OS_CBK_IDLE_CODE)
  #undef      OS_STOP_SEC_OS_CBK_IDLE_CODE

#elif defined (OS_START_SEC_OS_CBK_INSHUTDOWN_CODE)
  #undef      OS_START_SEC_OS_CBK_INSHUTDOWN_CODE
#elif defined (OS_STOP_SEC_OS_CBK_INSHUTDOWN_CODE)
  #undef      OS_STOP_SEC_OS_CBK_INSHUTDOWN_CODE

#elif defined (OS_START_SEC_OS_CBK_STACKOVERRUNHOOK_CODE)
  #undef      OS_START_SEC_OS_CBK_STACKOVERRUNHOOK_CODE
#elif defined (OS_STOP_SEC_OS_CBK_STACKOVERRUNHOOK_CODE)
  #undef      OS_STOP_SEC_OS_CBK_STACKOVERRUNHOOK_CODE

#else
  #error No section in Os_MemMap was matched
#endif
