

#ifndef DCMDSPOBD_MODE1_PRIV_H
#define DCMDSPOBD_MODE1_PRIV_H

#if(DCM_CFG_DSP_OBDMODE1_ENABLED != DCM_CFG_OFF)

#define DCM_OBDMODE01_REQ_LEN_MIN   0x00u
#define DCM_OBDMODE01_REQ_LEN_MAX   0x07u
#define DCM_OBDMODE01_SUPPPID       0x20u
#define DCM_SUPPORT_INFO_BITMASK    0x80u

#endif

#endif
