#if !defined (VSTDLIB_CFG_H)
#define VSTDLIB_CFG_H

#define VSTDLIB_USE_LIBRARY_FUNCTIONS STD_OFF
#define VSTDLIB_RUNTIME_OPTIMIZATION STD_ON
#define VSTDLIB_USE_JUMPTABLES STD_ON
#define VSTDLIB_DEV_ERROR_DETECT STD_OFF
#define VSTDLIB_DEV_ERROR_REPORT STD_OFF
#define VSTDLIB_VERSION_INFO_API STD_OFF
#define VSTDLIB_DUMMY_STATEMENT(v) (void)(v)
#define VSTDLIB_CFG_MAJOR_VERSION     (2u)
#define VSTDLIB_CFG_MINOR_VERSION     (0u)

#endif

