

#ifndef DCMDSPUDS_TRANSFERDATA_PRIV_H
#define DCMDSPUDS_TRANSFERDATA_PRIV_H

#if(DCM_CFG_DSP_TRANSFERDATA_ENABLED != DCM_CFG_OFF)
typedef enum{
    DCM_DSP_TRANSFERDATA_IDLE = 0
   ,   DCM_DSP_TRANSFERDATA_CHECKACCESS
   ,   DCM_DSP_TRANSFERDATA_READWRITE
   ,   DCM_DSP_TRANSFERDATA_ERROR
}Dcm_DspTransferDataStates_ten;

#define DCM_TRANSFERDATAUPLOAD_MIN_LEN              0x01u
#define DCM_TRANSFERDATADOWNLOAD_MIN_LEN              0x02u
#endif

#endif

