

#ifndef DCMDSPUDS_RMBA_PUB_H
#define DCMDSPUDS_RMBA_PUB_H

#if((DCM_CFG_DSP_READMEMORYBYADDRESS_ENABLED != DCM_CFG_OFF)||(DCM_CFG_DSP_TRANSFERDATA_ENABLED!= DCM_CFG_OFF))

typedef enum{
    DCM_RMBA_SUPPORT_OK
   ,   DCM_RMBA_SUPPORT_SESSION_VIOLATED
   ,   DCM_RMBA_SUPPORT_SECURITY_VIOLATED
   ,   DCM_RMBA_SUPPORT_CONDITION_VIOLATED
}Dcm_RmbaSupportRet_t;

#endif

#endif

