

#ifndef DCMDSPUDS_RMBA_PRIV_H
#define DCMDSPUDS_RMBA_PRIV_H

#if(DCM_CFG_DSP_READMEMORYBYADDRESS_ENABLED != DCM_CFG_OFF)

typedef enum{
    DCM_DSP_RMBA_IDLE = 0
   ,   DCM_DSP_RMBA_VALDATALEN
   ,   DCM_DSP_RMBA_CHECKACCESS
   ,   DCM_DSP_RMBA_READDATAREC
}Dcm_DspRmbaStates_ten;

#define DCM_DSP_RMBA_MINREQLEN 		0x03u
#endif

#endif

