

#ifndef DCMDSPOBD_MODE8_PRIV_H
#define DCMDSPOBD_MODE8_PRIV_H

#if(DCM_CFG_DSP_OBDMODE8_ENABLED != DCM_CFG_OFF)

#define DCM_OBDMODE08_SUPPTID     0x20u
#define DCM_OBDMODE08_REQ_LEN_MIN 0x00u
#define DCM_OBDMODE08_REQ_LEN_MAX 0x07u

#endif

#endif

