

#ifndef DCMDSPUDS_WMBA_PRIV_H
#define DCMDSPUDS_WMBA_PRIV_H

#if(DCM_CFG_DSP_WRITEMEMORYBYADDRESS_ENABLED != DCM_CFG_OFF)

typedef enum{
    DCM_DSP_WMBA_IDLE = 0
   ,   DCM_DSP_WMBA_VALDATALEN
   ,   DCM_DSP_WMBA_CHECKACCESS
   ,   DCM_DSP_WMBA_WRITEDATAREC
}Dcm_DspWmbaStates_ten;

#define DCM_DSP_WMBA_MINREQLEN 0x04u

#endif

#endif
