

#ifndef DEM_CFG_ENVDID_H
#define DEM_CFG_ENVDID_H

#define DEM_CFG_ENVDID2DATAELEMENT \
{ \
   DEM_DATAELEM_DEMDATAELEMENTCLASS_VEHICLESPEED,                                       \
   DEM_DATAELEM_DEMDATAELEMENTCLASS_ENGINESPEED,                                       \
   DEM_DATAELEM_DEMDATAELEMENTCLASS_AMBIENTTEMPERATURE,                                       \
   DEM_DATAELEM_DEMDATAELEMENTCLASS_VEHICLEMODE,   DEM_DATAELEM_DEMDATAELEMENTCLASS_HVSOC,   DEM_DATAELEM_DEMDATAELEMENTCLASS_LVBATTERYVOLTAGE,   DEM_DATAELEM_DEMDATAELEMENTCLASS_VEHICLESPEED,   DEM_DATAELEM_DEMDATAELEMENTCLASS_AMBIENTTEMPERATURE,   DEM_DATAELEM_DEMDATAELEMENTCLASS_ECUMODE_ROADMODE_LLSTATUS,   DEM_DATAELEM_DEMDATAELEMENTCLASS_OCCDATE,   DEM_DATAELEM_DEMDATAELEMENTCLASS_OCCTIME,   DEM_DATAELEM_DEMDATAELEMENTCLASS_TIREPRESS,   DEM_DATAELEM_DEMDATAELEMENTCLASS_TIRETEMP,                                       \
   0 \
}

#define DEM_DID_VEHICLESPEED         1
#define DEM_DID_ENGINESPEED         2
#define DEM_DID_AMBIENTTEMPERATURE         3
#define DEM_DID_DEMDIDCLASS_RIVIANSNAPSHOT         4

#define DEM_CFG_ENVDID \
{ \
   { 0, 0 } \
   ,{ 1, 3329 }       \
   ,{ 2, 3328 }       \
   ,{ 3, 3327 }       \
   ,{ 13, 1 }       \
}

#define DEM_CFG_ENVDID_ARRAYLENGTH  (4+1)

#endif

