

#ifndef DCMDSPUDS_TP_PRIV_H
#define DCMDSPUDS_TP_PRIV_H

#if(DCM_CFG_DSP_TESTERPRESENT_ENABLED != DCM_CFG_OFF || DCM_CFG_DSP_TESTERPRESENTSB_ENABLED != DCM_CFG_OFF)
#define DCM_TPR_REQ_LEN              0x01u
#define DCM_TPR_POSITIVE_RESP_LEN    0x01u
#define DCM_TPR_POSITION_SUBFUNC     0x00u
#define DCM_TPR_RESP_REQUIRED        0x00u
#endif

#endif

