

#ifndef DEM_CFG_ENVFREEZEFRAME_H
#define DEM_CFG_ENVFREEZEFRAME_H

#define DEM_CFG_ENVFREEZEFRAME2DID \
{ \
   DEM_DID_DEMDIDCLASS_RIVIANSNAPSHOT,  \
   0 \
}

#define DEM_FREEZEFRAME_FREEZEFRAMEDATASET_RIVIANSNAPSHOT         1

#define DEM_CFG_ENVFREEZEFRAME \
{ \
   { 0,0 }\
   ,{ 1, 32 }\
}

#define DEM_CFG_ENVFREEZEFRAME_ARRAYLENGTH  (1+1)

#endif

