#ifndef DEM_CFG_EVBUFF_H
#define DEM_CFG_EVBUFF_H

#define DEM_CFG_DEBUGDATA_BEFOREINIT_ON   STD_ON
#define DEM_CFG_DEBUGDATA_BEFOREINIT_OFF  STD_OFF
#define DEM_CFG_DEBUGDATA_BEFOREINIT   DEM_CFG_DEBUGDATA_BEFOREINIT_ON
#define DEM_CFG_FFPRESTORAGESUPPORT_OFF  STD_OFF
#define DEM_CFG_FFPRESTORAGESUPPORT_ON   STD_ON
#define DEM_CFG_FFPRESTORAGESUPPORT  DEM_CFG_FFPRESTORAGESUPPORT_ON
#define DEM_CFG_FFPRESTORAGE_NONVOLATILE_OFF  STD_OFF
#define DEM_CFG_FFPRESTORAGE_NONVOLATILE_ON   STD_ON
#define DEM_CFG_FFPRESTORAGE_NONVOLATILE  DEM_CFG_FFPRESTORAGE_NONVOLATILE_OFF
#define DEM_CFG_FFPRESTORAGE_NONVOLATILE_IMMEDIATE_OFF  STD_OFF
#define DEM_CFG_FFPRESTORAGE_NONVOLATILE_IMMEDIATE_ON   STD_ON
#define DEM_CFG_FFPRESTORAGE_NONVOLATILE_IMMEDIATE  DEM_CFG_FFPRESTORAGE_NONVOLATILE_IMMEDIATE_OFF
#define DEM_CFG_EVBUFF_SIZE   1u
#define DEM_CFG_PRESTORED_FF_SIZE   1u
#define DEM_CFG_SUPPORT_PROJECTSPECIFIC_FAILUREMEMORY    FALSE
#define DEM_CFG_CONSISTENCY_CHECK_OFF          0u
#define DEM_CFG_CONSISTENCY_CHECK_ON           1u
#define DEM_CFG_SUPPORT_PROJECTSPECIFIC_CONSISTENCYCHECK    DEM_CFG_CONSISTENCY_CHECK_OFF
#define DEM_CFG_EVBUFF_DELAY_SET_WAITINGFORMONITORING  255u

#endif

