

#ifndef COM_PBCFG_INTERNALID_H
#define COM_PBCFG_INTERNALID_H

#define     ComConf_ComIPdu_Internal_TPMS_ApplicationCyclic_Can_Network_0_CANNODE_0               0
#define     ComConf_ComIPdu_Internal_TPMS_Status_Can_Network_0_CANNODE_0               1
#define     ComConf_ComIPdu_Internal_TPMS_TirePT_Can_Network_0_CANNODE_0               2
#define     ComConf_ComIPdu_Internal_TPMS_ApplicationResponse_Can_Network_0_CANNODE_0               3

#define     ComConf_ComIPdu_Internal_BCM_PowerMode_Can_Network_0_CANNODE_0               0
#define     ComConf_ComIPdu_Internal_CGW_EPOCHTime_Can_Network_0_CANNODE_0               1
#define     ComConf_ComIPdu_Internal_CGW_ESP_WheelPulses_Can_Network_0_CANNODE_0               2
#define     ComConf_ComIPdu_Internal_CGW_ODO_Can_Network_0_CANNODE_0               3
#define     ComConf_ComIPdu_Internal_CGW_TPMS_Application_Req_Can_Network_0_CANNODE_0               4
#define     ComConf_ComIPdu_Internal_CGW_VCU_Ambient_Info_Can_Network_0_CANNODE_0               5
#define     ComConf_ComIPdu_Internal_CGW_VCU_Powertrain_Info_Can_Network_0_CANNODE_0               6
#define     ComConf_ComIPdu_Internal_CGW_VCU_WhlSpd_F_Can_Network_0_CANNODE_0               7
#define     ComConf_ComIPdu_Internal_CGW_VCU_WhlSpd_R_Can_Network_0_CANNODE_0               8
#define     ComConf_ComIPdu_Internal_CGW_VehicleSpeed_Can_Network_0_CANNODE_0               9
#define     ComConf_ComIPdu_Internal_RdcData_TPMS_Can_Network_0_CANNODE_0               10

#define     ComSignal_Internal_TPMS_AppCyclic               0
#define     ComSignal_Internal_TPMS_Tire_Ref_Press_RR               1
#define     ComSignal_Internal_TPMS_TempWarning_RL               2
#define     ComSignal_Internal_TPMS_TempWarning_FR               3
#define     ComSignal_Internal_TPMS_Val_FR               4
#define     ComSignal_Internal_TPMS_Status_RR               5
#define     ComSignal_Internal_TPMS_Tire_Ref_Press_RL               6
#define     ComSignal_Internal_TPMS_Tire_Ref_Press_FR               7
#define     ComSignal_Internal_TPMS_Tire_Ref_Press_FL               8
#define     ComSignal_Internal_TPMS_Locate_Status               9
#define     ComSignal_Internal_TPMS_Learn_Status               10
#define     ComSignal_Internal_TPMS_TempWarning_RR               11
#define     ComSignal_Internal_TPMS_TempWarning_FL               12
#define     ComSignal_Internal_TPMS_InflationMonitoring_Status               13
#define     ComSignal_Internal_TPMS_Val_RL               14
#define     ComSignal_Internal_TPMS_Val_RR               15
#define     ComSignal_Internal_TPMS_Val_FL               16
#define     ComSignal_Internal_TPMS_Status_RL               17
#define     ComSignal_Internal_TPMS_Status_FL               18
#define     ComSignal_Internal_TPMS_Status_FR               19
#define     ComSignal_Internal_TPMS_TireT_RR               20
#define     ComSignal_Internal_TPMS_TireT_FR               21
#define     ComSignal_Internal_TPMS_TireT_FL               22
#define     ComSignal_Internal_TPMS_TireP_RR               23
#define     ComSignal_Internal_TPMS_TireP_RL               24
#define     ComSignal_Internal_TPMS_TireP_FL               25
#define     ComSignal_Internal_TPMS_TireT_RL               26
#define     ComSignal_Internal_TPMS_TireP_FR               27
#define     ComSignal_Internal_TPMS_AppResponse               28

#define     ComSignal_Internal_BCM_PowerMode_Status               0
#define     ComSignal_Internal_BCM_PowerMode_Prop_Status               1
#define     ComSignal_Internal_BCM_PowerMode_HV_Status               2
#define     ComSignal_Internal_BCM_PowerMode_PAD_Status               3
#define     ComSignal_Internal_BCM_PowerMode_Ctr               4
#define     ComSignal_Internal_CGW_TCU_EPOCHTime_Valid               5
#define     ComSignal_Internal_CGW_TCU_EPOCHTime_Msec               6
#define     ComSignal_Internal_CGW_EPOCHTime_Ctr               7
#define     ComSignal_Internal_CGW_TCU_EPOCHTime_Sec               8
#define     ComSignal_Internal_CGW_ESP_WheelPulses_Ctr               9
#define     ComSignal_Internal_CGW_ESP_WheelSpdSenPulse_FR               10
#define     ComSignal_Internal_CGW_ESP_WheelSpdSenPulse_RR               11
#define     ComSignal_Internal_CGW_ESP_WheelSpdSenPulse_FL               12
#define     ComSignal_Internal_CGW_ESP_WheelSpdSenPulseQual_RR               13
#define     ComSignal_Internal_CGW_ESP_WheelSpdSenPulseQual_RL               14
#define     ComSignal_Internal_CGW_ESP_WheelSpdSenPulseQual_FR               15
#define     ComSignal_Internal_CGW_ESP_WheelSpdSenPulseQual_FL               16
#define     ComSignal_Internal_CGW_ESP_WheelPulses_CSum               17
#define     ComSignal_Internal_CGW_ESP_WheelSpdSenPulse_RL               18
#define     ComSignal_Internal_CGW_Odometer               19
#define     ComSignal_Internal_CGW_TPMS_Application_Req_Cmd               20
#define     ComSignal_Internal_CGW_VCU_AmbientTemp_Qualifier               21
#define     ComSignal_Internal_CGW_VCU_Ambient_Info_Ctr               22
#define     ComSignal_Internal_CGW_VCU_AmbientTemp               23
#define     ComSignal_Internal_CGW_VCU_Powertrain_Info_CSum               24
#define     ComSignal_Internal_CGW_VCU_GearStatus_Qualifier               25
#define     ComSignal_Internal_CGW_VCU_Powertrain_Info_Ctr               26
#define     ComSignal_Internal_CGW_VCU_GearStatus               27
#define     ComSignal_Internal_CGW_VCU_WhlSpd_FL_Valid               28
#define     ComSignal_Internal_CGW_VCU_WhlSpd_FR               29
#define     ComSignal_Internal_CGW_VCU_WhlSpd_FL               30
#define     ComSignal_Internal_CGW_VCU_WhlDir_FR               31
#define     ComSignal_Internal_CGW_VCU_WhlDir_FL               32
#define     ComSignal_Internal_CGW_VCU_WhlSpd_FR_Valid               33
#define     ComSignal_Internal_CGW_VCU_WhlSpd_Ctr_F               34
#define     ComSignal_Internal_CGW_VCU_WhlSpd_CSum_F               35
#define     ComSignal_Internal_CGW_VCU_WhlSpd_RR               36
#define     ComSignal_Internal_CGW_VCU_WhlSpd_RL_Valid               37
#define     ComSignal_Internal_CGW_VCU_WhlSpd_RL               38
#define     ComSignal_Internal_CGW_VCU_WhlDir_RR               39
#define     ComSignal_Internal_CGW_VCU_WhlDir_RL               40
#define     ComSignal_Internal_CGW_VCU_WhlSpd_RR_Valid               41
#define     ComSignal_Internal_CGW_VCU_WhlSpd_Ctr_R               42
#define     ComSignal_Internal_CGW_VCU_WhlSpd_CSum_R               43
#define     ComSignal_Internal_CGW_VehSpeed               44
#define     ComSignal_Internal_CGW_VehSpeed_CSum               45
#define     ComSignal_Internal_CGW_VehSpeed_Ctr               46
#define     ComSignal_Internal_CGW_VehSpeed_InfoQualifier               47
#define     ComSignal_Internal_User_Defined_Val5               48
#define     ComSignal_Internal_User_Defined_Val3               49
#define     ComSignal_Internal_User_Defined_Val2               50
#define     ComSignal_Internal_TyreId_High               51
#define     ComSignal_Internal_User_Defined_Val4               52
#define     ComSignal_Internal_User_Defined_Val1               53
#define     ComSignal_Internal_PackageId               54
#define     ComSignal_Internal_TyreId_Low               55

#endif
