

#ifndef DCMDSPOBD_MODE2_PRIV_H
#define DCMDSPOBD_MODE2_PRIV_H

#if(DCM_CFG_DSP_OBDMODE2_ENABLED != DCM_CFG_OFF)

#define DCM_DSPMODE02_PID02   0x02u
#define MAX_PID_LENGTH_DATA   0xffu
#define DCM_OBDMODE02_SUPPPID 0x20u

#endif

#endif

