MKLINK /D common            ..\..\..\..\repo_submodules\common\pRealEcu_R2023.10.18
MKLINK /D EcuabCanIf        ..\..\..\..\repo_submodules\EcuabCanIf\pRealEcu_R2023.10.18
MKLINK /D EcuabCanTrcv      ..\..\..\..\repo_submodules\EcuabCanTrcv\pRealEcu_R2023.09.21
MKLINK /D EcuabFee          ..\..\..\..\repo_submodules\EcuabFee\pRealEcu_R2023.09.21
MKLINK /D EcuabMemIf        ..\..\..\..\repo_submodules\EcuabMemIf\pRealEcu_R2023.09.21
MKLINK /D LibAutosar        ..\..\..\..\repo_submodules\LibAutosar\pRealEcu_R2023.10.18
MKLINK /D McalAdc           ..\..\..\..\repo_submodules\McalAdc\pRealEcu_R2023.09.21
MKLINK /D McalCan           ..\..\..\..\repo_submodules\McalCan\pRealEcu_R2023.10.18
MKLINK /D McalDio           ..\..\..\..\repo_submodules\McalDio\pRealEcu_R2023.10.18
MKLINK /D McalFls           ..\..\..\..\repo_submodules\McalFls\pRealEcu_R2023.10.18
MKLINK /D McalGpt           ..\..\..\..\repo_submodules\McalGpt\pRealEcu_R2023.10.18
MKLINK /D McalLin           ..\..\..\..\repo_submodules\McalLin\pRealEcu_R2023.09.21
MKLINK /D McalMcu           ..\..\..\..\repo_submodules\McalMcu\pRealEcu_R2023.10.18
MKLINK /D McalWdg           ..\..\..\..\repo_submodules\McalWdg\pRealEcu_R2023.09.21
MKLINK /D SwcApplDcm        ..\..\..\..\repo_submodules\SwcApplDcm\pRealEcu_R2023.10.18
MKLINK /D SwcApplDem        ..\..\..\..\repo_submodules\SwcApplDem\pRealEcu_R2023.10.18
MKLINK /D SwcApplEcuM       ..\..\..\..\repo_submodules\SwcApplEcuM\pRealEcu_R2023.09.21
MKLINK /D SwcApplNvM        ..\..\..\..\repo_submodules\SwcApplNvM\pRealEcu_R2023.10.18
MKLINK /D SwcApplTpms       ..\..\..\..\repo_submodules\SwcApplTpms\pRealEcu_R2023.09.21
MKLINK /D SwcServiceBswM    ..\..\..\..\repo_submodules\SwcServiceBswM\pRealEcu_R2023.09.21
MKLINK /D SwcServiceCanSm   ..\..\..\..\repo_submodules\SwcServiceCanSm\pRealEcu_R2023.10.18
MKLINK /D SwcServiceCanTp   ..\..\..\..\repo_submodules\SwcServiceCanTp\pRealEcu_R2023.10.18
MKLINK /D SwcServiceCom     ..\..\..\..\repo_submodules\SwcServiceCom\pRealEcu_R2023.10.18
MKLINK /D SwcServiceComM    ..\..\..\..\repo_submodules\SwcServiceComM\pRealEcu_R2023.10.18
MKLINK /D SwcServiceDcm     ..\..\..\..\repo_submodules\SwcServiceDcm\pRealEcu_R2023.10.18
MKLINK /D SwcServiceDem     ..\..\..\..\repo_submodules\SwcServiceDem\pRealEcu_R2023.10.18
MKLINK /D SwcServiceDet     ..\..\..\..\repo_submodules\SwcServiceDet\pRealEcu_R2023.09.21
MKLINK /D SwcServiceEcuM    ..\..\..\..\repo_submodules\SwcServiceEcuM\pRealEcu_R2023.10.18
MKLINK /D SwcServiceFiM     ..\..\..\..\repo_submodules\SwcServiceFiM\pRealEcu_R2023.09.21
MKLINK /D SwcServiceNvM     ..\..\..\..\repo_submodules\SwcServiceNvM\pRealEcu_R2023.10.18
MKLINK /D SwcServiceOs      ..\..\..\..\repo_submodules\SwcServiceOs\pRealEcu_R2023.10.18
MKLINK /D SwcServicePduR    ..\..\..\..\repo_submodules\SwcServicePduR\pRealEcu_R2023.10.18
MKLINK /D SwcServiceSchM    ..\..\..\..\repo_submodules\SwcServiceSchM\pRealEcu_R2023.09.21
MKLINK /D SwcServiceStartUp ..\..\..\..\repo_submodules\SwcServiceStartUp\pRealEcu_R2023.10.18
